springdoc:
  show-actuator: true
  api-docs:
    groups:
      enabled: true
    version: openapi_3_1
  swagger-ui:
    use-root-path: true
spring:
  application:
    name: template-spring-webflux
  data:
    mongodb:
      authentication-database: root
      uri: mongodb://admin:password@localhost:27017/spring-webflux?authSource=admin
      password: password
      username: admin
server:
  port: 8080
  http2:
    enabled: true
logging:
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info